name: Update README with Daily Log

on:
  schedule:
    - cron: '0 16 * * *'  # 每天 UTC 16:00（北京时间 00:00）运行
  workflow_dispatch:  # 允许手动触发

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 拉取所有分支信息

      - name: Ensure mogu branch exists
        run: |
          if git ls-remote --heads origin mogu | grep mogu; then
            echo "mogu 分支已存在，切换到 mogu"
            git checkout mogu
          else
            echo "mogu 分支不存在，创建并推送"
            git checkout -b mogu
            git push origin mogu
          fi

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Get Current Date
        id: date
        run: echo "TODAY=$(date '+%Y-%m-%d')" >> $GITHUB_ENV

      - name: Check if today's log exists
        id: check_log
        run: |
          if grep -q "## $TODAY" README.md; then
            echo "今天的记录已存在，跳过更新"
            echo "SKIP_UPDATE=true" >> $GITHUB_ENV
          else
            echo "今天的记录不存在，继续更新"
            echo "SKIP_UPDATE=false" >> $GITHUB_ENV
          fi

      - name: Update README.md
        if: env.SKIP_UPDATE == 'false'
        run: |
          echo "## $TODAY" >> README.md
          echo "- 缪哥又没学 git" >> README.md
          echo "" >> README.md

      - name: Commit and Push Changes
        if: env.SKIP_UPDATE == 'false'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git add README.md
          git commit -m "更新 README: $TODAY" || echo "No changes to commit"
          git push origin mogu

